# Sinamor — PDF report generator
# Uses fpdf2 for lightweight PDF creation compatible with Streamlit downloads

from fpdf import FPDF
import re


def generate_pdf_report(session_summary: str) -> bytes:
    """
    Generates a downloadable PDF from chat session text.
    Strips HTML tags and sanitizes unicode for latin-1 FPDF compatibility.
    """
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", size=20, style="B")
    pdf.set_text_color(19, 136, 8)
    pdf.cell(0, 12, text="MindMitra - Wellness Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Decorative line
    pdf.set_draw_color(255, 153, 51)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(50, 50, 50)

    # Strip any leftover HTML tags
    clean_text = re.sub(r"<[^>]+>", "", session_summary)

    # FPDF default fonts only support latin-1 — replace unsupported chars
    safe_text = clean_text.encode("latin-1", "replace").decode("latin-1")

    pdf.multi_cell(0, 7, text=safe_text)

    # Footer note
    pdf.ln(10)
    pdf.set_font("Helvetica", size=9, style="I")
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, text="Generated by MindMitra GNDEC Edition | Confidential", align="C")

    return bytes(pdf.output())
