[theme]
primaryColor = "#FF9933"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFCFF"
textColor = "#222222"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
